Project/RHMN/force-app/main/default/objects/IBC_Attendee__c/IBC_Attendee__c.object-meta.xml
<CustomObject>
    <label>IBC Attendee</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>IBC Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IBC Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IBC_Attendee__c/fields/IBC_Attendee_Name__c.field-meta.xml
<CustomField>
    <fullName>IBC_Attendee_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IBC Attendee Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>IBC_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

Project/RHMN/force-app/main/default/objects/IBC_Attendee__c/fields/IBC_Meeting__c.field-meta.xml
<CustomField>
    <fullName>IBC_Meeting__c</fullName>
    <label>IBC Meeting</label>
    <referenceTo>IBC_Meeting__c</referenceTo>
    <relationshipLabel>IBC Attendees</relationshipLabel>
    <relationshipName>IBC_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Desktop/Project/RHMN/force-app/main/default/objects/IBC_Meeting__c/IBC_Meeting__c.object-meta.xml
<CustomObject>
    <label>IBC Meeting</label>
    <nameField>
        <displayFormat>Meeting-{0000}</displayFormat>
        <label>IBC Meeting</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IBC Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project/RHMN/force-app/main/default/objects/IBC_Meeting__c/fields/Polling_Response__c.field-meta.xml
<CustomField>
    <fullName>Polling_Response__c</fullName>
    <label>Polling Response</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Response</fullName>
                <default>true</default>
                <label>No Response</label>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>No-Qualified</fullName>
            </value>
            <value>
                <fullName>Excused</fullName>
            </value>
            <value>
                <fullName>Vacation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Attendees_Addition_Cntrlr.cls
/**********************************************

* Class: Attendee_Addition_Cntrlr (Attendee_Addition_Helper)
* PageName : Attendee_Addition.vfp
* Objective: Helper will provide the required methods that helps in fetching the Users attended the meeting
* Test Class:   need to write
* Developer: Anil

**********************************************/ 

	Public class Attendees_Addition_Cntrlr {
    
        Public IBC_Attendee__c attendee {set;get;}
        Public Integer rowIndex		{set;get;}
        Public List<IBC_Attendee__c> slctdAtndRecs {set;get;}
        Public Map<String, IBC_Attendee__c> slctdAtndRecs_mp {set;get;}
        Public String currentRecordId {get;set;}
        public List<IBC_Attendee__c> exstedAttndes	{set;get;}
        
        
        public Attendees_Addition_Cntrlr(ApexPages.StandardController controller) {
            currentRecordId=ApexPages.CurrentPage().getparameters().get('id');
            attendee=new IBC_Attendee__c();
            attendee.IBC_Meeting__c = currentRecordId;
            slctdAtndRecs=new List<IBC_Attendee__c>();
            fetchAttendees();
        } //EO Attendees_Addition_Cntrlr Constructor
        
        
        // This helps in fetching new attendee 
        Public void addRow(){
            slctdAtndRecs.add(attendee);
            attendee = new IBC_Attendee__c();
            attendee.IBC_Meeting__c = currentRecordId;
        }  //EO addRow
        
        // This for saving the list of attendees and navigating to the detail page of the record
        Public PageReference saveAttendees(){
            if(slctdAtndRecs.size() > 0)
                Insert slctdAtndRecs;
            PageReference pageRef = new PageReference('/'+currentRecordId);
            pageRef.setRedirect(true);
            return pageRef;
        } //EO saveAttendees
        
        //This helps in the deletion of the attendees that are fetched
        Public PageReference deleteRow(){
            rowIndex = Integer.valueOf(ApexPages.currentPage().getParameters().get('rowIndex'));
            slctdAtndRecs.remove(rowIndex);
            return null;
        } // EO deleteRow
        
        
        // This helps in navigating to the object list view page
        Public PageReference cancel(){
            PageReference page=new PageReference('/a03/o');
            page.setRedirect(true);
            return page;
        } // EO cancel
        
        
        // This helps in fetching the existing attendees for the particular meeting
        Public void fetchAttendees(){
            exstedAttndes=[select id,IBC_Attendee_Name__r.name,Polling_Response__c from IBC_Attendee__c where IBC_Meeting__c=:currentRecordId];
        } // EO fetchAttendees
	}