Project/RHMN/force-app/main/default/objects/IBC_Attendee__c/IBC_Attendee__c.object-meta.xml
<CustomObject>
    <label>IBC Attendee</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>IBC Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IBC Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IBC_Attendee__c/fields/IBC_Attendee_Name__c.field-meta.xml
<CustomField>
    <fullName>IBC_Attendee_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IBC Attendee Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>IBC_Attendees</relationshipName>
    <type>Lookup</type>
</CustomField>

Project/RHMN/force-app/main/default/objects/IBC_Attendee__c/fields/IBC_Meeting__c.field-meta.xml
<CustomField>
    <fullName>IBC_Meeting__c</fullName>
    <label>IBC Meeting</label>
    <referenceTo>IBC_Meeting__c</referenceTo>
    <relationshipLabel>IBC Attendees</relationshipLabel>
    <relationshipName>IBC_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Desktop/Project/RHMN/force-app/main/default/objects/IBC_Meeting__c/IBC_Meeting__c.object-meta.xml
<CustomObject>
    <label>IBC Meeting</label>
    <nameField>
        <displayFormat>Meeting-{0000}</displayFormat>
        <label>IBC Meeting</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IBC Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project/RHMN/force-app/main/default/objects/IBC_Meeting__c/fields/Polling_Response__c.field-meta.xml
<CustomField>
    <fullName>Polling_Response__c</fullName>
    <label>Polling Response</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Response</fullName>
                <default>true</default>
                <label>No Response</label>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>No-Qualified</fullName>
            </value>
            <value>
                <fullName>Excused</fullName>
            </value>
            <value>
                <fullName>Vacation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_Attendees_Addition_Cntrlr.cls
@isTest
public class Test_Attendees_Addition_Cntrlr {
    @isTest static void addRow_Test(){
        IBC_Attendee__c test_Attendee=new IBC_Attendee__c();
        
        test_Attendee.IBC_Attendee_Name__c='0052v00000ebgEPAAY';
        test_Attendee.Polling_Response__c='Excused';
	      test_Attendee.IBC_Meeting__c='a032v00003Ei1ujAAB';
 	         insert test_Attendee;
   
     integer i=[select count() from IBC_Attendee__c where IBC_Attendee_Name__c=:test_Attendee.IBC_Attendee_Name__c and Polling_Response__c=:test_Attendee.Polling_Response__c];
    	system.assertEquals(i, 1);	
    }
      
	}